### ISSUE TITLE
npm package does not install correctly

### ISSUE THREAD

**Issue by tmaximini** [Kikobeats/react-clap-button#48]
<img width="1180" alt="Bildschirmfoto 2020-02-08 um 10 50 07" src="https://user-images.githubusercontent.com/570544/74083122-d17a7200-4a60-11ea-8d57-2b148c7af5ec.png">

`sh: babel: command not found` - I assume this is because of the `postinstall` npm script which calls `npm run build` on the machine it installs to, and babel is just a dev dependency. not everyone using this package will have babel installed. Why not babel it before publishing?

**Comment by Kikobeats** [comment]
yep, you're right, I think `postinstall` can be removed since this module was written in ES6, so using it in a common react workflow means eventually will be transpiled according to with every project babel settings.

Can you make a PR? also this `lib` reference need to be removed https://github.com/Kikobeats/react-clap-button/blob/master/package.json#L6

**Comment by tmaximini** [comment]
ok, I will make a PR 👍

**Comment by tmaximini** [comment]
The problem is that most workflows do not transpile stuff from node_modules again. I think pre-publish transpilation and then only publish /lib would be the way to go.

**Comment by Kikobeats** [comment]
@tmaximini 

I took your PR as inspiration and I improved bundle system at `react-clap-button@1.2.1`

https://github.com/Kikobeats/react-clap-button/commit/f311545c071c45d3391048e387c29275f58a0301

Can you told me if it's working fine for you?

**Comment by tmaximini** [comment]
yes, works perfectly now!

**Comment by Kikobeats** [comment]
awesome 🎉
